/** 
 * file wb_array_test.c 
 * 
 * This file was generated by classgenerator from array_test.txt. 
 * DO NOT CHANGE MANUALLY! 
 * 
 * Created by Mick Hawkins at 22:12, 14/10/2015 
 * Copyright (c) 2015 Mick Hawkins 
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met: 
 * 
 * 1. Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer. 
 * 
 * 2. Redistributions in binary form must reproduce the above 
 *    copyright notice, this list of conditions and the following 
 *    disclaimer in the documentation and/or other materials 
 *    provided with the distribution. 
 * 
 * 3. All advertising materials mentioning features or use of this 
 *    software must display the following acknowledgement: 
 * 
 *    This product includes software developed by Mick Hawkins. 
 * 
 * 4. Neither the name of the author nor the names of contributors 
 *    may be used to endorse or promote products derived from this 
 *    software without specific prior written permission. 
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 * 'AS IS' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR 
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING 
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 * 
 * ----------------------------------------------------------------------- 
 * This program is free software; you can redistribute it and/or 
 * modify it under the above terms or under the terms of the GNU 
 * General Public License as published by the Free Software Foundation; 
 * either version 2 of the License, or (at your option) any later version. 
 * 
 * This program is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
 * GNU General Public License for more details. 
 * 
 * You should have received a copy of the GNU General Public License 
 * along with this program; if not, see http://www.gnu.org/licenses/ 
 * or write to the Free Software Foundation, Inc., 51 Franklin Street, 
 * Fifth Floor, Boston, MA  02110-1301, USA. 
 */ 


#include "wb_array_test.h" 
#include "gusimplewhiteboard.h" 
#include <stdio.h> 
#include <string.h> 
#include <stdlib.h> 

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION 

/** convert to a description string */  
const char* wb_array_test_description(const struct wb_array_test* self, char* descString, size_t bufferSize) 
{ 
    size_t len; 

    gu_strlcat(descString, "pressed=", bufferSize); 
    gu_strlcat(descString, pressed ? "true" : "false", bufferSize); 
    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        len = gu_strlcat(descString, "array16={", bufferSize); 
    } 

    int array16_first = 0; 

    for (int i = 0; i < ARRAY_TEST_ARRAY16_ARRAY_SIZE; i++) 
    { 
        if (len < bufferSize) 
        { 
            if (array16_first == 1) 
            { 
                len = gu_strlcat(descString, ",", bufferSize); 
            } 
            snprintf(descString+len, bufferSize-len, "%d", array16[i]); 
        } 
        array16_first = 1; 
    } 
    gu_strlcat(descString, "}", bufferSize); 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        len = gu_strlcat(descString, "array32={", bufferSize); 
    } 

    int array32_first = 0; 

    for (int i = 0; i < ARRAY_TEST_ARRAY32_ARRAY_SIZE; i++) 
    { 
        if (len < bufferSize) 
        { 
            if (array32_first == 1) 
            { 
                len = gu_strlcat(descString, ",", bufferSize); 
            } 
            snprintf(descString+len, bufferSize-len, "%d", array32[i]); 
        } 
        array32_first = 1; 
    } 
    gu_strlcat(descString, "}", bufferSize); 

	return descString; 
} 

/** convert to a string */  
const char* wb_array_test_to_string(const struct wb_array_test* self, char* toString, size_t bufferSize) 
{ 
    size_t len; 

    gu_strlcat(toString, pressed ? "true" : "false", bufferSize); 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        len = gu_strlcat(descString, "{", bufferSize); 
    } 

    int array16_first = 0; 

    for (int i = 0; i < ARRAY_TEST_ARRAY16_ARRAY_SIZE; i++) 
    { 
        if (len < bufferSize) 
        { 
            if (array16_first == 1) 
            { 
                len = gu_strlcat(descString, ",", bufferSize); 
            } 
            snprintf(descString+len, bufferSize-len, "%d", array16[i]); 
        } 
        array16_first = 1; 
    } 
    gu_strlcat(descString, "}", bufferSize); 

    len = gu_strlcat(descString, ", ", bufferSize); 

    if (len < bufferSize) 
    { 
        len = gu_strlcat(descString, "{", bufferSize); 
    } 

    int array32_first = 0; 

    for (int i = 0; i < ARRAY_TEST_ARRAY32_ARRAY_SIZE; i++) 
    { 
        if (len < bufferSize) 
        { 
            if (array32_first == 1) 
            { 
                len = gu_strlcat(descString, ",", bufferSize); 
            } 
            snprintf(descString+len, bufferSize-len, "%d", array32[i]); 
        } 
        array32_first = 1; 
    } 
    gu_strlcat(descString, "}", bufferSize); 

    return toString; 
} 

/** convert from a string */  
struct wb_array_test* wb_array_test_from_string(struct wb_array_test* self, const char* str) 
{ 
    char* strings[ARRAY_TEST_NUMBER_OF_VARIABLES]; 
    const char s[3] = ", ";  /// delimeter 
    const char e[2] = "=";   /// delimeter 
    char* tokenS, *tokenE; 
    char* saveptr = NULL; 

    memset(strings, 0, sizeof(strings)); 

    for (int i = 0; i < ARRAY_TEST_NUMBER_OF_VARIABLES; i++) 
    { 
        int j = i; 
        tokenS = strtok_r(str, s, &saveptr); 

        if (tokenS) 
        { 
            tokenE = strchr(tokenS, e); 

            if (tokenE == NULL) 
            { 
                 tokenE = tokenS; 
            } 
            else 
            { 
                 tokenE++; 

                if (strcmp(tokenS, "pressed") == 0) 
                { 
                    j = 0; 
                } 
                else if (strcmp(tokenS, "array16") == 0) 
                { 
                    j = 1; 
                } 
                else if (strcmp(tokenS, "array32") == 0) 
                { 
                    j = 2; 
                } 
            } 

            strings[j] = tokenE; 
        } 
    } 

    if (strings[0] != NULL) 
        set_pressed(strings[0]); 

    const char a[2] = ","; 

    char array16_output[GU_SIMPLE_WHITEBOARD_BUFSIZE];
    memset(array16_output, 0, sizeof(array16_output)); 

    size_t array16_input_length = strlen(strings[1]); 

    if (array16_input_length > 0) 
        strcpy(array16_output, ++strings[1]]);          // remove the { 

    if (array16_input_length > 1) 
        array16_output[array16_input_length-2] = "/0";  // remove the } 

    size_t array16_smallest = (strlen(array16_output)+1)/2 < ARRAY_TEST_ARRAY16_ARRAY_SIZE ? (strlen(array16_output)+1)/2 : ARRAY_TEST_ARRAY16_ARRAY_SIZE; 

    for (int i = 0; i < array16_smallest; i++) 
    { 
        char* token = strchr(array16_output, a); 
        if (token != NULL) 
            set_array16((int16_t)atoi(token, i); 
    } 

    char array32_output[GU_SIMPLE_WHITEBOARD_BUFSIZE];
    memset(array32_output, 0, sizeof(array32_output)); 

    size_t array32_input_length = strlen(strings[2]); 

    if (array32_input_length > 0) 
        strcpy(array32_output, ++strings[2]]);          // remove the { 

    if (array32_input_length > 1) 
        array16_output[array32_input_length-2] = "/0";  // remove the } 

    size_t array32_smallest = (strlen(array32_output)+1)/2 < ARRAY_TEST_ARRAY32_ARRAY_SIZE ? (strlen(array16_output)+1)/2 : ARRAY_TEST_ARRAY32_ARRAY_SIZE; 

    for (int i = 0; i < array32_smallest; i++) 
    { 
        char* token = strchr(array32_output, a); 
        if (token != NULL) 
            set_array32((int32_t)atoi(token, i); 
    } 

    return self 
}; 
#endif /// WHITEBOARD_POSTER_STRING_CONVERSION 
