/**
*  /file guwhiteboardtypelist_tcp_generated.h
*
*  Created by Carl Lusty in 2013.
*  Copyright (c) 2013-2016 Carl Lusty and Rene Hexel
*  All rights reserved.
*/


#ifndef GUWHITEBOARD_TCP_TYPELIST_H_
#define GUWHITEBOARD_TCP_TYPELIST_H_

#include "gugenericwhiteboardobject.h"
#include "gutcpinjectionwhiteboardobject.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wold-style-cast"


//Generated on: Tue Sep 19 06:45:41 2017
//Generated by user: callum

namespace guWhiteboard
{

extern "C"
{
#include "guwhiteboardtypelist_c_generated.h"
}

	/** WB Ptr Class: Demo @brief class:wb_demo, nonatomic, Demo, "A comment" */ 

        class Demo_iTCP: public injection_whiteboard_object<class wb_demo > { 
	public: 
		/** Constructor: Demo */ 
		Demo_iTCP(const char *hostname = (const char *)"localhost", bool is_async = true) : injection_whiteboard_object<class wb_demo >(hostname, kDemo_v, is_async) {} 
	};

}

#pragma clang diagnostic pop

#endif
