/*
 * file FieldBall.hpp
 *
 * This file was generated by classgenerator from fieldBall.gen.
 * DO NOT CHANGE MANUALLY!
 *
 * Copyright © 2021 Carl Lusty. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials
 *    provided with the distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgement:
 *
 *        This product includes software developed by Carl Lusty.
 *
 * 4. Neither the name of the author nor the names of contributors
 *    may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER
 * OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * -----------------------------------------------------------------------
 * This program is free software; you can redistribute it and/or
 * modify it under the above terms or under the terms of the GNU
 * General Public License as published by the Free Software Foundation;
 * either version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see http://www.gnu.org/licenses/
 * or write to the Free Software Foundation, Inc., 51 Franklin Street,
 * Fifth Floor, Boston, MA  02110-1301, USA.
 *
 */

#ifndef guWhiteboard_FieldBall_h
#define guWhiteboard_FieldBall_h

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION
#include <cstdlib>
#include <string.h>
#include <sstream>
#endif

#include <gu_util.h>
#include "wb_field_ball.h"

#undef guWhiteboard_FieldBall_DEFINED
#define guWhiteboard_FieldBall_DEFINED

#undef FieldBall_DEFINED
#define FieldBall_DEFINED

namespace guWhiteboard {

    /**
     * Provides a C++ wrapper around `wb_field_ball`.
     */
    class FieldBall: public wb_field_ball {

    private:

        /**
         * Set the members of the class.
         */
        void init(enum BallOptions t_sightingType = NoBallDetected, uint16_t t_x = 0, uint16_t t_y = 0, uint16_t t_r = 0) {
            set_sightingType(t_sightingType);
            set_x(t_x);
            set_y(t_y);
            set_r(t_r);
        }

    public:

        /**
         * Create a new `FieldBall`.
         */
        FieldBall(enum BallOptions t_sightingType = NoBallDetected, uint16_t t_x = 0, uint16_t t_y = 0, uint16_t t_r = 0) {
            this->init(t_sightingType, t_x, t_y, t_r);
        }

        /**
         * Copy Constructor.
         */
        FieldBall(const FieldBall &t_other): wb_field_ball() {
            this->init(t_other.sightingType(), t_other.x(), t_other.y(), t_other.r());
        }

        /**
         * Copy Constructor.
         */
        FieldBall(const struct wb_field_ball &t_other): wb_field_ball() {
            this->init(t_other.sightingType, t_other.x, t_other.y, t_other.r);
        }

        /**
         * Copy Assignment Operator.
         */
        FieldBall &operator = (const FieldBall &t_other) {
            this->init(t_other.sightingType(), t_other.x(), t_other.y(), t_other.r());
            return *this;
        }

        /**
         * Copy Assignment Operator.
         */
        FieldBall &operator = (const struct wb_field_ball &t_other) {
            this->init(t_other.sightingType, t_other.x, t_other.y, t_other.r);
            return *this;
        }

        bool operator ==(const FieldBall &t_other) const
        {
            return sightingType() == t_other.sightingType()
                && x() == t_other.x()
                && y() == t_other.y()
                && r() == t_other.r();
        }

        bool operator !=(const FieldBall &t_other) const
        {
            return !(*this == t_other);
        }

        bool operator ==(const wb_field_ball &t_other) const
        {
            return *this == FieldBall(t_other);
        }

        bool operator !=(const wb_field_ball &t_other) const
        {
            return !(*this == t_other);
        }

        enum BallOptions & sightingType()
        {
            return wb_field_ball::sightingType;
        }

        const enum BallOptions & sightingType() const
        {
            return wb_field_ball::sightingType;
        }

        void set_sightingType(const enum BallOptions &t_newValue)
        {
            wb_field_ball::sightingType = t_newValue;
        }

        uint16_t & x()
        {
            return wb_field_ball::x;
        }

        const uint16_t & x() const
        {
            return wb_field_ball::x;
        }

        void set_x(const uint16_t &t_newValue)
        {
            wb_field_ball::x = t_newValue;
        }

        uint16_t & y()
        {
            return wb_field_ball::y;
        }

        const uint16_t & y() const
        {
            return wb_field_ball::y;
        }

        void set_y(const uint16_t &t_newValue)
        {
            wb_field_ball::y = t_newValue;
        }

        uint16_t & r()
        {
            return wb_field_ball::r;
        }

        const uint16_t & r() const
        {
            return wb_field_ball::r;
        }

        void set_r(const uint16_t &t_newValue)
        {
            wb_field_ball::r = t_newValue;
        }

#ifdef WHITEBOARD_POSTER_STRING_CONVERSION
        /**
         * String Constructor.
         */
        FieldBall(const std::string &t_str) {
            this->init();
            this->from_string(t_str);
        }

        std::string description() {
#ifdef USE_WB_FIELD_BALL_C_CONVERSION
            char buffer[FIELDBALL_DESC_BUFFER_SIZE];
            wb_field_ball_description(this, buffer, sizeof(buffer));
            std::string descr = buffer;
            return descr;
#else
            std::ostringstream ss;
            switch (this->sightingType()) {
                case GreatBall:
                {
                    ss << "sightingType=" << "GreatBall";
                    break;
                }
                case NoBallDetected:
                {
                    ss << "sightingType=" << "NoBallDetected";
                    break;
                }
                case RegularBall:
                {
                    ss << "sightingType=" << "RegularBall";
                    break;
                }
                case UltraBall:
                {
                    ss << "sightingType=" << "UltraBall";
                    break;
                }
            }
            ss << ", ";
            ss << "x=" << static_cast<unsigned>(this->x());
            ss << ", ";
            ss << "y=" << static_cast<unsigned>(this->y());
            ss << ", ";
            ss << "r=" << static_cast<unsigned>(this->r());
            return ss.str();
#endif /// USE_WB_FIELD_BALL_C_CONVERSION
        }

        std::string to_string() {
#ifdef USE_WB_FIELD_BALL_C_CONVERSION
            char buffer[FIELDBALL_TO_STRING_BUFFER_SIZE];
            wb_field_ball_to_string(this, buffer, sizeof(buffer));
            std::string toString = buffer;
            return toString;
#else
            std::ostringstream ss;
            switch (this->sightingType()) {
                case GreatBall:
                {
                    ss << "GreatBall";
                    break;
                }
                case NoBallDetected:
                {
                    ss << "NoBallDetected";
                    break;
                }
                case RegularBall:
                {
                    ss << "RegularBall";
                    break;
                }
                case UltraBall:
                {
                    ss << "UltraBall";
                    break;
                }
            }
            ss << ", ";
            ss << static_cast<unsigned>(this->x());
            ss << ", ";
            ss << static_cast<unsigned>(this->y());
            ss << ", ";
            ss << static_cast<unsigned>(this->r());
            return ss.str();
#endif /// USE_WB_FIELD_BALL_C_CONVERSION
        }

#ifdef USE_WB_FIELD_BALL_C_CONVERSION
        void from_string(const std::string &t_str) {
            wb_field_ball_from_string(this, t_str.c_str());
#else
        void from_string(const std::string &t_str) {
            char * str_cstr = const_cast<char *>(t_str.c_str());
            size_t temp_length = strlen(str_cstr);
            int length = (temp_length <= INT_MAX) ? static_cast<int>(static_cast<ssize_t>(temp_length)) : -1;
            if (length < 1 || length > FIELDBALL_DESC_BUFFER_SIZE) {
                return;
            }
            char var_str_buffer[FIELDBALL_DESC_BUFFER_SIZE + 1];
            char* var_str = &var_str_buffer[0];
            char key_buffer[13];
            char* key = &key_buffer[0];
            int bracecount = 0;
            int startVar = 0;
            int index = 0;
            int startKey = 0;
            int endKey = -1;
            int varIndex = 0;
            if (index == 0 && str_cstr[0] == '{') {
                index = 1;
            }
            startVar = index;
            startKey = startVar;
            do {
                for (int i = index; i < length; i++) {
                    index = i + 1;
                    if (bracecount == 0 && str_cstr[i] == '=') {
                        endKey = i - 1;
                        startVar = index;
                        continue;
                    }
                    if (bracecount == 0 && isspace(str_cstr[i])) {
                        startVar = index;
                        if (endKey == -1) {
                            startKey = index;
                        }
                        continue;
                    }
                    if (bracecount == 0 && str_cstr[i] == ',') {
                        index = i - 1;
                        break;
                    }
                    if (str_cstr[i] == '{') {
                        bracecount++;
                        continue;
                    }
                    if (str_cstr[i] == '}') {
                        bracecount--;
                        if (bracecount < 0) {
                            index = i - 1;
                            break;
                        }
                    }
                    if (i == length - 1) {
                        index = i;
                    }
                }
                if (endKey >= startKey && endKey - startKey < length) {
                    strncpy(key, str_cstr + startKey, static_cast<size_t>((endKey - startKey) + 1));
                    key[(endKey - startKey) + 1] = 0;
                } else {
                    key[0] = 0;
                }
                strncpy(var_str, str_cstr + startVar, static_cast<size_t>((index - startVar) + 1));
                var_str[(index - startVar) + 1] = 0;
                bracecount = 0;
                index += 2;
                startVar = index;
                startKey = startVar;
                endKey = -1;
                if (strlen(key) > 0) {
                    if (0 == strcmp("sightingType", key)) {
                        varIndex = 0;
                    } else if (0 == strcmp("x", key)) {
                        varIndex = 1;
                    } else if (0 == strcmp("y", key)) {
                        varIndex = 2;
                    } else if (0 == strcmp("r", key)) {
                        varIndex = 3;
                    } else {
                        varIndex = -1;
                    }
                }
                switch (varIndex) {
                    case -1: { break; }
                    case 0:
                    {
                        if (strcmp("GreatBall", var_str) == 0) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wbad-function-cast"
                        this->set_sightingType(GreatBall);
#pragma clang diagnostic pop
                        } else if (strcmp("NoBallDetected", var_str) == 0) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wbad-function-cast"
                        this->set_sightingType(NoBallDetected);
#pragma clang diagnostic pop
                        } else if (strcmp("RegularBall", var_str) == 0) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wbad-function-cast"
                        this->set_sightingType(RegularBall);
#pragma clang diagnostic pop
                        } else if (strcmp("UltraBall", var_str) == 0) {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wbad-function-cast"
                        this->set_sightingType(UltraBall);
#pragma clang diagnostic pop
                        } else {
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wbad-function-cast"
                        this->set_sightingType(static_cast<enum BallOptions>(atoi(var_str)));
#pragma clang diagnostic pop
                        }
                        break;
                    }
                    case 1:
                    {
                        this->set_x(static_cast<uint16_t>(atoi(var_str)));
                        break;
                    }
                    case 2:
                    {
                        this->set_y(static_cast<uint16_t>(atoi(var_str)));
                        break;
                    }
                    case 3:
                    {
                        this->set_r(static_cast<uint16_t>(atoi(var_str)));
                        break;
                    }
                }
                if (varIndex >= 0) {
                    varIndex++;
                }
            } while(index < length);
#endif /// USE_WB_FIELD_BALL_C_CONVERSION
        }
#endif /// WHITEBOARD_POSTER_STRING_CONVERSION
    };

} /// namespace guWhiteboard

#endif /// guWhiteboard_FieldBall_h
