/**
 *  /file guwhiteboardtypelist_generated.h
 *
 *  Created by Carl Lusty in 2013.
 *  Copyright (c) 2013-2016 Carl Lusty and Rene Hexel
 *  All rights reserved.
 */


#ifndef GUWHITEBOARD_TYPELIST_H_
#define GUWHITEBOARD_TYPELIST_H_

#include "gugenericwhiteboardobject.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpadded"


//Generated on: Tue Sep 19 06:45:41 2017
//Generated by user: callum

namespace guWhiteboard
{

extern "C"
{
#include "guwhiteboardtypelist_c_generated.h"
}

	/** WB Ptr Class: Demo @brief class:wb_demo, nonatomic, Demo, "A comment" */ 

        class Demo_t: public generic_whiteboard_object<class wb_demo > { 
	public: 
		/** Constructor: Demo */ 
		Demo_t(gu_simple_whiteboard_descriptor *wbd = NULL) : generic_whiteboard_object<class wb_demo >(wbd, kDemo_v, false) {} 
	};

}

#pragma clang diagnostic pop

#endif
