/**
 *  /file guwhiteboardtypelist_c_generated.h
 *
 *  Created by Carl Lusty in 2013.
 *  Copyright (c) 2013-2016 Carl Lusty and Rene Hexel
 *  All rights reserved.
 */


#ifndef GUWHITEBOARD_TYPELIST_C_H_
#define GUWHITEBOARD_TYPELIST_C_H_


#define WANT_WB_STRINGS

#define GSW_NUM_TYPES_DEFINED 1

#if GSW_NUM_TYPES_DEFINED > GSW_NUM_RESERVED
#error *** Error: gusimplewhiteboard: The number of defined types exceeds the total number of reserved types allowed. Increase GSW_NUM_RESERVED to solve this.
#endif
//Generated on: Tue Sep 19 06:45:41 2017
//Generated by user: callum

       /** All the message 'types' for the class based whiteboard */
	typedef enum wb_types
        {
                kDemo_v = 0	///< class:wb_demo, nonatomic, Demo, "A comment"
        } WBTypes; ///< All the message 'types' for the class based whiteboard 

        extern const char *WBTypes_stringValues[GSW_NUM_TYPES_DEFINED];
        extern const char *WBTypes_typeValues[GSW_NUM_TYPES_DEFINED];
  #endif
